server.port=${PORT:8080}


# Telegram Bot Configuration
telegram.bot.token=${TELEGRAM_BOT_TOKEN:8791717729:AAEQxO94ZfFHmLYBOG_1hqG3JYSKHytuyDs}
telegram.admin.chatId=${TELEGRAM_ADMIN_CHAT_ID:1911247574,5880756540}
